[package]
name = "crates"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.28.0"
macroquad = {git="https://github.com/not-fl3/macroquad.git", rev="76e693fc8344424c10e7f62e9d9442c06fb9e851"}
# macroquad = {git="https://github.com/not-fl3/macroquad.git", branch="master"}
rand = "0.8.5"
